Style/Documentation:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Security/Open:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Rails/RedundantForeignKey:
  Enabled: false

Rails/ApplicationMailer:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
